# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: v3
kind: repository
metadata:
  name: github.com/spendesk/terraform-provider-debezium-postgres
  owner: "infrastructure"
